import Foundation

public class Week1_Day2_Q2 {
    // MARK: - Q.2.Even Fibonacci numbers

    //  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    //           1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    //  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    public static func evenFibonacci() -> Int {
        var current = 1
        var previous = 1
        var totalEven = 0
        while current + previous <= 4000000 {
            let next = current + previous
            previous = current
            current = next
            if next%2 == 0 {
                totalEven += next
            }
        }
        return totalEven
    }
}
